### ISSUE TITLE
less2css.org domain needs renewal

### ISSUE THREAD

**Issue by dzoba** [less/old-lesscss.org#111]
http://less2css.org/

![image](https://f.cloud.github.com/assets/857664/1853531/8fd665e8-770d-11e3-9586-09c56e68ae5a.png)

**Comment by seven-phases-max** [comment]
Thanks, but this probably should go there: [less2css.org at GitHub](https://github.com/brian-frichette/less-preview)

**Comment by lukeapage** [comment]
I've raised an issue there. Thanks for bringing it up.

**Comment by lukeapage** [comment]
its been fixed

**Comment by jonschlinkert** [comment]
@dzoba yes! thanks!
