### ISSUE TITLE
Old lesscss.org?

### ISSUE THREAD

**Issue by michalswietochowski** [less/old-lesscss.org#113]
What happened to http://lesscss.org? It looks like an old version is public (maximum less.js version is 1.5.0-b4 there).

**Comment by jonschlinkert** [comment]
Can you clarify? Is there a link on the new site with an outdated version of Less.js?

**Comment by michalswietochowski** [comment]
I don't know how did this website (lesscss.org) look earlier, but yesterday it was single page with black header, and there was full documentation, button to download v1.6.1 etc. Today it is blue, there is no documentation (links don't work, for ex. http://lesscss.org/index.html#docs), and there is "See what's new in v1.5.0-b4...".
![screenshot 2014-01-15 at 16 24 55](https://f.cloud.github.com/assets/655689/1921406/a1dcbe98-7df9-11e3-9343-a2ee105cdccb.png)

**Comment by Synchro** [comment]
That is an old version - it's missing some changes I committed a week or so ago.

**Comment by jonschlinkert** [comment]
> links don't work

We'll get the version fixed, but can you specify the links that aren't working? the link that you posted works fine for me

**Comment by michalswietochowski** [comment]
Left side menu on main page:
Getting started
http://lesscss.org/index.html#synopsis
http://lesscss.org/index.html#usage
http://lesscss.org/index.html#docs
http://lesscss.org/index.html#reference
http://lesscss.org/index.html#about
http://lesscss.org/index.html#third-parties

All these anchors don't work for me - there are no sections to which they (I think) were meant to point. 
Tested on Safari 7.0.1, Chrome 32.0.1700.77 on OS X 10.9.1.

These pages work, but there are some glitches with affix sidebar:
http://lesscss.org/features.html
http://lesscss.org/functions.html

**Comment by lukeapage** [comment]
any idea whats going on? somehow lesscss.org is pointing at a old version, but I don't know how that would have happened.

http://less.github.io/

has the updated site and @cloudhead was going to transfer lesscss.org to point directly at that..

**Comment by lukeapage** [comment]
and also www.lesscss.org has disappeared (lesscss.org brings up the old new site) ... @cloudhead please could you fix or revert?

**Comment by jonschlinkert** [comment]
don't we have to setup a CNAME file in the root of the project?

**Comment by jonschlinkert** [comment]
See: https://github.com/assemble/assemble-docs/blob/gh-pages/CNAME
