### ISSUE TITLE
Slogan or tag line

### ISSUE THREAD

**Issue by Soviut** [less/old-lesscss.org#114]
Every other open source library has a slogan or tag line, Django's is "The web framework for perfectionists with deadlines". Ruby on Rails says "Web development that doesn't hurt". And so on.

I think it would be helpful to have a similar slogan for LESS. Some of the most obvious ones being "do more with less" or "less is more", etc. The only issue being that we'd need to work in what LESS actually does. Perhaps "A CSS compiler that let's you do more".

**Comment by matthew-dean** [comment]
I think "Do more with Less" is a clear winner (IMO).

**Comment by Soviut** [comment]
I agree. I want to put it out there for review though, because I still think there might be a way to work in what LESS actually is.

"LESS: the css compiler that lets you do more" works in those regards, but there's room for improvement.

**Comment by SomMeri** [comment]
Quick ideas:
- more style with less css
- more style with less style sheets
- less code to do more

**Comment by matthew-dean** [comment]
Hmm....
- Create CSS with Less
- Create a more beautiful web with Less
- Less: It's like CSS, only better.

**Comment by Soviut** [comment]
@SomMeri Yeah, that's on the right track. I like the "more style" idea.

@matthew-dean I think your first is too literal and doesn't explain why anyone would want to use LESS over raw CSS, and the second feels too ambiguous. This is still a good direction though.

**Comment by Synchro** [comment]
"Do more with Less" is just too good to pass up, we've got to use it somewhere!

Maybe just combine it with a simple description like: "Do more with Less, the advanced CSS compiler".

A few random ideas (cheese alert!):
- Unmess your CSS with Less
- Less: CSS without the mess
- More miles per style with Less
- More style, less mess
- Less: CSS++

**Comment by jonschlinkert** [comment]
> Do more with Less

:+1:  please let me run a trademark search do a "right to use" before we jump into anything

**Comment by jonschlinkert** [comment]
I like that phrase though, I've seen it somewhere let's hope we can use it!

**Comment by SomMeri** [comment]
@Synchro Those with rhymes are great :)

**Comment by lukeapage** [comment]
I've been trying to think of a tagline that is not as meaningless e.g. I could easily describe sass as "do lots more in css" whereas less has a slightly different approach, but I can't think of a nifty way of summing that up without sounding daunting!
Also worth noting is the original acronym for less, so I guess the website used to say "LEaner Style Sheets" - but we don't have to incorporate or use that if we don't have to.
Finally.. shouldn't this issue and discussion be on less-docs?

**Comment by Soviut** [comment]
I think it belong here because it's going to show up on the main website more than it will in the documentation.

**Comment by matthew-dean** [comment]
@lukeapage A tagline doesn't have to be descriptive. That's what descriptions are for. A tagline is part of the brand. Think of Apple product taglines. "1,000 songs in your pocket" could have been ANY mp3 player, but only one player associated the tag with the brand. I also like "Do more with Less" because of the play on words. It implies that there are more powerful techniques you can do with styling without being too on the nose. And with the way the sentence is phrased, it implies simplicity. So it hits the right emotional notes.

What we could do is have the tagline "Do more with Less", and then immediately follow with a "one-liner" that's descriptive.

**Comment by Soviut** [comment]
Agreed. I think "Do more with less" is just too good a slogan to pass up. It gets the _philosophy_ of LESS across which is important for newcomers. Following with descriptions and examples will make it abundantly clear how it will fulfill the slogan's promise.

**Comment by seven-phases-max** [comment]
<img src="http://www.savagechickens.com/images/chickenmoreless.jpg" />
You'll find [more](http://rlv.zcache.com/less_is_more_t_shirt-rbf7acbb1912742eea03c426942d9760c_jyr6b_1024.jpg) with G. and I wouldn't use it... These are already too overused stock phrases these days.

**Comment by lukeapage** [comment]
moved here
https://github.com/less/less-docs/issues/99
