### ISSUE TITLE
Missing variable in documentation for "mix()"

### ISSUE THREAD

**Issue by rjelte** [less/old-lesscss.org#16]
On lesscss.org, the following line explains the use of the mix function:

mix(@color1, @color2);    // return a mix of @color1 and @color2 

However, mix requires a 3rd parameter, a percentage, like follows:
mix(@color1, @color2, 50%);    // return a mix of @color1 and @color2

**Comment by danielcha** [comment]
+1 came here to report the same issue.... I think LESS is awesome... however I wasted over an hour manually calculating the right hex colors .... because the documentation was missing the %.

Please update this and prefend other people from wasting their time! :-)

**Comment by lukeapage** [comment]
Closing this.. will take the pull
