### ISSUE TITLE
Mixins with tag selectors

### ISSUE THREAD

**Issue by pakamore** [less/old-lesscss.org#17]
Should LESS support tag + class rulesets inside rulesets? Example:
# menu a {

  **a**.bordered;
}

All examples in documentation refer to using single selector by class. But logically _.bordered_ may have different rules for _a.bordered_, _span.bordered_, etc., so the ruleset to be included may have a tag selector as well.

In our case coder sets rulesets in a form of a tag and class that together are imported to the CMS as a format to use in content formatting, so all user classes have a tag name in front.

**Comment by lukeapage** [comment]
I think this might belong in the main less repo?
