### ISSUE TITLE
Math operations issue on Javascript evaluation

### ISSUE THREAD

**Issue by floq-design** [less/old-lesscss.org#19]
Hi
I've run across an issue that had me stuck for quite some time with javascript operations.

First with a variable calculated with javascript:

<pre>@var: `Math.ceil((250 * 100) / 1030)`;</pre>

Then when 'hacking' a unit symbol to the computed value as so doesn't work:

<pre>@var: @cta * 1%</pre>

However this way round does:

<pre>@var: 1% * @cta</pre>

**Comment by lukeapage** [comment]
this is definitely already raised on

https://github.com/cloudhead/less.js/issues

which is the place for less.js issues.

This is just for documentation.
