### ISSUE TITLE
Basic Features Documentation

### ISSUE THREAD

**Issue by SomMeri** [less/old-lesscss.org#37]
I'm writing some Less language documentation as part of less4j project. It is more a draft then finished thing by now, but I would be willing to contribute it if there is interest. 

What I wrote up to now:
- https://github.com/SomMeri/less4j/wiki/Supported-Less-Language
- https://github.com/SomMeri/less4j/wiki/Quirks

I'm writing it as I'm learning and less seems to have many surprises, so if there are inaccuracies I apologize in advance.

**Comment by lukeapage** [comment]
Hey @SomMeri closing this as this repo is no more.. It doesn't look like there is anything to move to less-docs, but please correct me if I'm wrong. Should any of the quirks be written up on the main site? Feel free to raise an issue on less-docs
