### ISSUE TITLE
Translation to Indonesian

### ISSUE THREAD

**Issue by bertzzie** [less/old-lesscss.org#38]
Hi,

I've been using LESS to build my blog and very satisfied with it. LESS is so good that I want more people to use it, so I think of a way to contribute. I decided to translate the LESS documentation to my native language (Indonesian) so that people in my country can learn to use LESS with less effort. I've done the translation of the LESS documentation to Indonesian, and hosted it here:

http://bertzzie.com/post/8/less-the-dynamic-stylesheet-language

http://bertzzie.com/post/7/dokumentasi-less-bahasa-indonesia

And I'm not sure how to notify you guys and to get it added into the main page. What should I do to get it added? Should I do the pull request myself?

Please tell me what should I do to help. I can send you pull request for the main site if you want. Thanks before.

**Comment by lukeapage** [comment]
Sorry I didn't answer this.. thanks for the pull request... will push to the site tonight after all the changes.
