### ISSUE TITLE
Wrong Content-Length

### ISSUE THREAD

**Issue by ciembor** [less/old-lesscss.org#44]
I get this when I try to visit main page:

```
ciembor@peace ~/lesscss.org> rackup config.ru 
>> Thin web server (v1.5.0 codename Knife)
>> Maximum connections set to 1024
>> Listening on 0.0.0.0:9292, CTRL+C to stop
!! Unexpected error while processing request: Content-Length header was 33193, but should be 33199
127.0.0.1 - - [18/Nov/2012 23:33:09] "GET / HTTP/1.1" 200 33193 0.0145
127.0.0.1 - - [18/Nov/2012 23:33:09] "GET / HTTP/1.1" 200 33193 0.0154
```

I'm going to publish Polish translation and I get similar error, but with higher difference between the expected and existing length:

```
!! Unexpected error while processing request: Content-Length header was 33995, but should be 34833
```

**Comment by lukeapage** [comment]
Debugging locally? I had no problem.. it looks like a thin problem?

**Comment by ciembor** [comment]
I run it on a Unicorn - it rendered, but the document was incomplete (lack of a tail). I don't know why the difference in my Polish translation is bigger than in the orginal, maybe it's because of encoding?

**Comment by lukeapage** [comment]
maybe, not sure what unicorn is.. did you get to the bottom of this? can I close it..?

**Comment by ciembor** [comment]
I had rendered it with Unicorn (http server), copied this missing fragment manualy and then I published it on gh-pages. But I don't know why this render failed, it's possible that someone will have the same problem in the future.

**Comment by lukeapage** [comment]
we now run off gh-pages and have a new site. closing.
