### ISSUE TITLE
better more complete documentation for options

### ISSUE THREAD

**Issue by lukeapage** [less/old-lesscss.org#53]

**Comment by lukeapage** [comment]
browser side done, would be good to have more info on serverside? low priority?

**Comment by matthew-dean** [comment]
Actually, it would be nice to know more about how the source files are consumed. There's a lot of assumptions about what people already know. Someone might be willing to jump into learning Node and doing a Node-based project, for example, if there were simple examples of usage.

The minimum is all the options that can be sent to parser. Even that could give example results. For instance, I don't fully understand how the paths option works, or what different syntaxes are allowed. There's a lot of black box processing which makes LESS integration daunting.

**Comment by lukeapage** [comment]
Yes, I think you are right.. I didn't know there was a paths option till 2
weeks ago.

The difficult bit is how to fit it in without crowding the usage section or
redesigning the site.
