### ISSUE TITLE
Lesscss.org does not render properly on Firefox 19.0.2

### ISSUE THREAD

**Issue by SomMeri** [less/old-lesscss.org#78]
Drop down menu is disconnected from top bar. It is impossible to click on individual chapters (variables, mixins etc), because the menu disappears whenever mouse leaves brown area.

![lesscss bug](https://f.cloud.github.com/assets/618879/323151/051c99e2-9a9d-11e2-99e7-58bfd439a395.png)

Mouse over the "language" menu item will render brown list of chapters, but when the mouse leave brown area, list of chapters disappear.

**Comment by lukeapage** [comment]
switched to new site
