### ISSUE TITLE
What is the license for this site, specifically hiless.css?

### ISSUE THREAD

**Issue by asolove** [less/old-lesscss.org#8]
I am interested in using hiless.js as part of an open-source documentation tool for less but I don't see a license for this site and don't want to use it inappropriately.

**Comment by cloudhead** [comment]
you mean hiless.js? you may use that freely—I haven't released it because it has some issues still with comment handling.

The site html/css and design may not be re-used in any way however, that's why there's no license.

Let us know about your project when it's ready!

**Comment by lukeapage** [comment]
@asolove did you get anything sorted here?
