### ISSUE TITLE
Could not get less.js to work on IE8

### ISSUE THREAD

**Issue by eytanchen** [less/old-lesscss.org#87]
I have read all the threads regarding less.js and IE8 and have tried all the solutions, with no luck. IE8 shows js error on less.js file (line 5660: head.removeChild(oldCss);).
I tried remarking this line - this prevented the error but no less rendering happened (page has no css).
Tried to remove all the HTML from the BODY (so to not have HTML5 issues though I have modernizer and html5shiv), tried to minimize the less file itself to only give the body a background - still, no error but no less rendering at all.
I am basically stuck and am one step from converting less to simple css, which really is a bummer cause it works great on all modern browsers!

Here is the link to my website (in development):
http://www.tyco.co.il/develop/

I would really appreciate any help! Thanks!

**Comment by lukeapage** [comment]
I think you raised this on the wrong repo, hence why it was ignore. sorry!
